baseURL: https://nikcodes.xyz/
languageCode: en-us
title: Nik Codes
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  description: "Nik personal website, here you can find all my projects, blog and art"
  keywords: [Blog, Portfolio, PaperMod, Art]
  author: Nicolas cesar sabbatini Vrech
  DateFormat: "2 January 2006"
  images: ["logo.svg", "logo.svg"]
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: true
  env: production
  ShowBreadCrumbs: true

  assets:
    favicon: "logo.svg"
    favicon16x16: "logo.svg"
    favicon32x32: "logo.svg"
    apple_touch_icon: "logo.svg"
    safari_pinned_tab: "logo.svg"

  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi there \U0001F44B!"
    subtitle: "My name is Nik, I’m a backend developer from Argentina and in my free time I do digital art"
    imageUrl: "logo.svg"
    imageWidth: 250
    imageHeight: 250
    imageTitle: Logo
    buttons:
      - name: Projets
        url: /projets/
      - name: Posts
        url: /posts/
      - name: Tags
        url: /tags/
      - name: Art
        url: /sketches-and-plotters/

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/nikcodes.xyz"
    - name: github
      url: "https://github.com/nicolas-sabbatini/"
    - name: itchio
      url: "https://nik-codes.itch.io/"
    - name: rss
      url: "index.xml"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  editPost:
    URL: "https://todo.sr.ht/~nik_codes/nikcodes_website"
    Text: "Submit a ticket"
    appendFilePath: false

menu:
  main:
    - identifier: about_me
      name: "about me"
      url: /about_me/
      weight: 1
    - identifier: projets
      name: projets
      url: /projets/
      weight: 10
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: my_art
      name: "my art"
      url: /sketches-and-plotters/
      weight: 40
    - identifier: search
      name: search
      url: /search/
      weight: 50
