baseURL: https://nikcodes.xyz/
languageCode: en-us
title: Nik Codes
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  description: "Nik personal website, here you can find all my projects and my blog"
  keywords: [ Blog, Portfolio, PaperMod ]
  author: Nicolas cesar sabbatini Vrech
  DateFormat: "2 January 2006"
  images: ["assets/img/logo.png", "assets/img/logo.png"]
  defaultTheme: dark
  disableThemeToggle: true
  ShowShareButtons: true
  env: production
  ShowBreadCrumbs: true

  assets:
    favicon: "assets/img/logo.png"
    favicon16x16: "assets/img/fav16x16.icon"
    favicon32x32: "assets/img/fav32x32.icon"
    apple_touch_icon: "assets/img/logo.png"
    safari_pinned_tab: "assets/img/logo.png"

  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi there \U0001F44B!"
    subtitle: "My name is Nik, I am full stack developer and I am trying to inspire people to code their dreams. "
    imageUrl: "assets/img/logo.png"
    imageWidth: 250
    imageHeight: 250
    imageTitle: Logo
    buttons:
      - name: Projets
        url: /projets/
      - name: Posts
        url: /posts/
      - name: Tags
        url: /tags/

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/nik_codes"
    - name: youtube
      url: "https://www.youtube.com/channel/UCmymYI9hAm98xJRjp7NN15w"
    - name: github
      url: "https://sr.ht/~nik_codes/"
    - name: itchio
      url: "https://nik-codes.itch.io/"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

  editPost:
    URL: "https://todo.sr.ht/~nik_codes/nikcodes_website"
    Text: "Submit a ticket"
    appendFilePath: false

menu:
  main:
    - identifier: projets
      name: projets
      url: /projets/
      weight: 10
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: archives
      url: /archives/
      weight: 40
    - identifier: search
      name: search
      url: /search/
      weight: 50

outputs:
    home:
        - HTML
        - RSS
        - JSON
